GET http://localhost:3000/employee

###
GET http://localhost:3000/employee/651fb6147faa80f7bb87ba47


###
POST http://localhost:3000/employee
Content-Type: application/json

{
    "employeeNumber": "ABC-125",
    "firstName": "MANNY",
    "middleName": "PACMAN",
    "lastName": "PACQUIAO",
    "dob": "04-11-1996",
    "gender": "Male",
    "maritalStatus": "Married",
    "regionCode": "06",
    "provinceCode": "0604",
    "cityCode": "060406",
    "barangayCode": "060406024",
    "tin": "222222222222",
    "sssId": "987654321",
    "hdmf": "567890123",
    "phic": "345678901",
    "email": "manny@gmail.com",
    "contactNo": "+63123545657",
    "isActive": true,
    "qualifiedDependents": [
    {
      "name": "Jane PACQUIAO",
      "dob": "2010-03-20",
      "relationship": "Child"
    },
    {
      "name": "Mary PACQUIAO",
      "dob": "2015-08-10",
      "relationship": "Child"
    }
  ],
  "trainingDetails": [
    {
      "trainingName": "Safety Training",
      "dateStart": "2022-06-15",
      "dateEnd": "2022-06-17",
      "certificateUrl": "https://example.com/certificate2.pdf",
      "remarks": "Passed"
    }
  ]
}

###
PATCH  http://localhost:3000/employee/651e4957648181bd15b3da56
Content-Type: : application/json

{
    "isActive": false,
}

###
DELETE http://localhost:3000/employee/651fb6147faa80f7bb87ba47
